import api from './index'

export const adminApi = {
  listNews(keyword, status, page = 1, size = 20) { return api.get('/admin/news/page', { params: { keyword, status, page, size } }) },
  getNews(id) { return api.get(`/admin/news/${id}`) },
  saveNews(data) { return data.id ? api.put(`/admin/news/${data.id}`, data) : api.post('/admin/news', data) },
  updateNews(id, data) { return api.put(`/admin/news/${id}`, data) },
  deleteNews(id) { return api.delete(`/admin/news/${id}`) },
  setNewsStatus(id, status) { return api.put(`/admin/news/${id}/status`, null, { params: { status } }) },
  listMatchOverrides() { return api.get('/admin/matches') },
  listCrawlerMatches(params = {}) { return api.get('/crawler/matches/db/page', { params }) },
  saveCrawlerMatch(data) { return api.post('/crawler/matches', data) },
  updateCrawlerMatch(id, data) { return api.put(`/crawler/matches/${id}/edit`, data) },
  deleteCrawlerMatch(id) { return api.delete(`/crawler/matches/${id}`) },
  saveMatchOverride(data) { return api.post('/admin/matches', data) },
  deleteMatchOverride(fixtureId) { return api.delete(`/admin/matches/${fixtureId}`) },
  updateUserRole(userId, role) { return api.put('/users/role', { userId, role }) },
  updateUserStatus(userId, status) { return api.put('/admin/users/status', { userId, status }) },
  listUsers(keyword) { return api.get('/admin/users', { params: { keyword } }) },
  listVideos(params = {}) { return api.get('/admin/videos', { params }) },
  saveVideo(data) { return data.id ? api.put(`/admin/videos/${data.id}`, data) : api.post('/admin/videos', data) },
  updateVideo(id, data) { return api.put(`/admin/videos/${id}`, data) },
  deleteVideo(id) { return api.delete(`/admin/videos/${id}`) },
  setVideoStatus(id, status) { return api.put(`/admin/videos/${id}/status`, null, { params: { status } }) },
  debugSeedVideo() { return api.post('/admin/videos/debug/seed') },
  getConfig() { return api.get('/admin/config') },
  saveConfig(data) { return api.put('/admin/config', data) },
  getLogs() { return api.get('/admin/config/logs') },
  syncFootballDataMatches() { return api.post('/crawler/sync/football-data') },
  syncJuheMatches() { return api.post('/crawler/sync/juhe') },
  syncCrawlerMatches() { return api.post('/crawler/sync/crawler') },
  syncTodayMatches() { return api.post('/crawler/sync/today') },
  syncUpcomingMatches() { return api.post('/crawler/sync/upcoming') },
  syncAllMatches() { return api.post('/crawler/sync/all') }
}
